WIP - refactor zscore code
Crunch-io/crunch-cube pull request #311
Opened 2021-05-26 02:17 UTC by gergness

Use the `*_bases` functions to unify the calculation of zscores. I haven't had time to write unit tests yet, but I think this simplifies the zscore code and will make it easier for me to further refactor after the `rows_margin` consolidation.

It does have 2 errors in exporter though, but the only difference is whether there's a single hyphen or multiple. For example:

```
E       -              7   First Mov a2           58.3           ----          100.0              A              -              -
E       +              7   First Mov a2           58.3           ----          100.0              A              -           ----
```

2021-05-26 09:40 UTC, ernestoarbitrio commented
> Use the `*_bases` functions to unify the calculation of zscores. I haven't had time to write unit tests yet, but I think this simplifies the zscore code and will make it easier for me to further refactor after the `rows_margin` consolidation.
> 
> It does have 2 errors in exporter though, but the only difference is whether there's a single hyphen or multiple. For example:
> 
> ```
> E       -              7   First Mov a2           58.3           ----          100.0              A              -              -
> E       +              7   First Mov a2           58.3           ----          100.0              A              -           ----
> ```
> 
> Definitely need to write unit tests, but wanted to send my progress so far so that you can look during your day. Maybe we can cafe when I get on tomorrow.

I think the errors are not releted to your changes but if you start your branch from master that includes my hypothesis testing changes that's the reason of the hyphens thing

2021-05-26 09:46 UTC, ernestoarbitrio requested changes
Looks good overall, just couple of comments

2021-05-26 15:07 UTC, gergness commented on src/cr/cube/matrix/measure.py
> +    def _zscore_calculation(self, counts, total, rowsum, colsum):
What do you think of `_calculate_zscores`? I feel like `_zscores` sounds like a property not a method?

2021-05-26 15:11 UTC, ernestoarbitrio commented on src/cr/cube/matrix/measure.py
> +    def _zscore_calculation(self, counts, total, rowsum, colsum):
yeah like it

2021-05-27 09:43 UTC, ernestoarbitrio approved these changes
LGTM

2021-05-27 19:29 UTC, merged