isort cr.cube
Crunch-io/crunch-cube pull request #336
Opened 2021-07-12 19:34 UTC by slobodan-ilic

2021-07-12 19:49 UTC, ernestoarbitrio approved these changes
Awesome 👏🏻

2021-07-12 21:58 UTC, scanny requested changes
Okay, now that I've seen all the fixes this made I feel a little better about it. The two configuration changes I've identified are must-haves, there are several unneeded changes when those are left out.

The only thing I still don't like is repeating the `from x.y.module import ...` prefix on imports that rename the imported item, like `from enums import MEASURES as M`. Maybe one of the configuration options can get rid of that.

2021-07-12 21:58 UTC, scanny commented on src/cr/cube/cube.py
> +)
This line was fine as it was. `isort` needs `-l 88` or `--line-length 88` to wrap at the same place as Black.

2021-07-12 21:58 UTC, scanny commented on src/cr/cube/cube.py
> +from cr.cube.enums import NUMERIC_MEASURES
This one was also fine as it was. Repeating the `from x.y.module import ...` prefix obscures the boundaries between source modules in the import list. Adding `--multi-line 8` will change it to the format we already use.

2021-07-13 17:30 UTC, scanny reviewed
Just this one change I see, otherwise these look real good, that's a lot of fixes it caught :)

2021-07-13 17:30 UTC, scanny commented on tests/integration/test_cube.py
> +from ..fixtures import OL  # overlaps
These comments should go above so these don't break onto separate redundant lines. Or maybe we just get rid of the comments altogether.

2024-02-15 08:38 UTC, ernestoarbitrio commented
@slobodan-ilic I'm gonna close this PR and open (soon) a new one with `isort` latest version.

2024-02-15 08:38 UTC, closed without merging